# Generated by Django 4.2.16 on 2024-10-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cursos", "0002_alter_curso_nivel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="data_do_curso",
            field=models.DateField(help_text="aaaa-mm-dd"),
        ),
    ]
